from numpy import True_
from sketchpy import canvas
from time import sleep
from time import time
# project = canvas.trace(img_path="ariva.jpg", zoom=8, scale=1)
# project.trace()


# ----------------------------------------------
first = canvas.sketch(x_offset=270, y_offset=330)
first.draw_fn(file="first", co=(24, 66, 39), mode=0)
sleep(0.5)
first.draw_fn(file="second", mode=1, thickness=3)
# # # ----------------------------------------------
secound = canvas.sketch(x_offset=150, y_offset=350)
secound.draw_fn(file="A_out", mode=1, thickness=2)
secound.draw_fn(file="A_in", mode=1, thickness=2)
sleep(0.15)
secound.draw_fn(file="R_out", mode=1, thickness=2)
secound.draw_fn(file="R_in", mode=1, thickness=2)
sleep(0.15)
secound.draw_fn(file="I", mode=1, thickness=2)
sleep(0.15)
secound.draw_fn(file="V", mode=1, thickness=2)
sleep(0.15)
secound.draw_fn(file="A_out_2", mode=1, thickness=2)
secound.draw_fn(file="A_in_2", mode=1, thickness=2)
sleep(0.15)
secound.draw_fn(file="Pra_1", mode=1, thickness=2)
sleep(0.15)
secound.draw_fn(file="A_out_3", mode=1, thickness=2)
secound.draw_fn(file="A_in_3", mode=1, thickness=2)
sleep(0.15)
secound.draw_fn(file="R_out_2", mode=1, thickness=2)
secound.draw_fn(file="R_in_2", mode=1, thickness=2)
sleep(0.15)
secound.draw_fn(file="V_2", mode=1, thickness=2)
sleep(0.15)
secound.draw_fn(file="Pra_2", mode=1, thickness=2)
# ------------------------------------------------
secound.draw_fn(file="A_out", mode=0, co=(46, 65, 39))
secound.draw_fn(file="A_in", mode=0, co=(255, 254, 255))
sleep(0.15)
secound.draw_fn(file="R_out", mode=0, co=(14, 78, 86))
secound.draw_fn(file="R_in", mode=0, co=(255, 254, 255))
sleep(0.15)
secound.draw_fn(file="I", mode=0, co=(83, 96, 42))
sleep(0.15)
secound.draw_fn(file="V", mode=0, co=(3, 122, 123))
sleep(0.15)
secound.draw_fn(file="A_out_2", mode=0, co=(2, 165, 188))
secound.draw_fn(file="A_in_2", mode=0, co=(255, 254, 255))
sleep(0.15)
secound.draw_fn(file="Pra_1", mode=0, co=(3, 110, 154))
sleep(0.15)
secound.draw_fn(file="A_out_3", mode=0, co=(0, 101, 138))
secound.draw_fn(file="A_in_3", mode=0, co=(255, 254, 255))
sleep(0.15)
secound.draw_fn(file="R_out_2", mode=0, co=(1, 136, 163))
secound.draw_fn(file="R_in_2", mode=0, co=(255, 254, 255))
sleep(0.15)
secound.draw_fn(file="V_2", mode=0, co=(2, 165, 188))
sleep(0.15)
secound.draw_fn(file="Pra_2", mode=0, co=(3, 110, 154))
# sleep(10)
# --------------------------------------------------------
secound.draw_fn(file="A_out", mode=1, thickness=2.5)
secound.draw_fn(file="A_in", mode=1, thickness=2.5)
sleep(0.15)
secound.draw_fn(file="R_out", mode=1, thickness=2.5)
secound.draw_fn(file="R_in", mode=1, thickness=2.5)
sleep(0.15)
secound.draw_fn(file="I", mode=1, thickness=2.5)
sleep(0.15)
secound.draw_fn(file="V", mode=1, thickness=2.5)
sleep(0.15)
secound.draw_fn(file="A_out_2", mode=1, thickness=2.5)
secound.draw_fn(file="A_in_2", mode=1, thickness=2.5)
sleep(0.15)
secound.draw_fn(file="Pra_1", mode=1, thickness=2.5)
sleep(0.15)
secound.draw_fn(file="A_out_3", mode=1, thickness=2.5)
secound.draw_fn(file="A_in_3", mode=1, thickness=2.5)
sleep(0.15)
secound.draw_fn(file="R_out_2", mode=1, thickness=2.5)
secound.draw_fn(file="R_in_2", mode=1, thickness=2.5)
sleep(0.15)
secound.draw_fn(file="V_2", mode=1, thickness=2.5)
sleep(0.15)
secound.draw_fn(file="Pra_2", mode=1, thickness=2.5)
sleep(10)
